[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sum_crate = { path = "../sum_crate" } # 因为sum_crate为本地库，所以指定为本地路径依赖